### ISSUE TITLE
Report builder should provide XML validation logic from AllureReportGenerator

### ISSUE THREAD

**Issue by vania-pooh** [allure-framework/allure-report-builder#1]
So far as we're using report builder everywhere in tools and plugins it would be great to have this functionality in builder. I would return a list of valid XML files as a result of processResults method.

**Comment by eroshenkoam** [comment]
resolved since https://github.com/allure-framework/allure-core/releases/tag/allure-core-1.4.10

**Comment by eroshenkoam** [comment]
close
